### ISSUE TITLE
Uncaught Error: Connection is closed.

### ISSUE THREAD

**Issue by trebolcinco** [liuderchi/ide-yaml#18] opened 2017-10-27 22:01 UTC
[Enter steps to reproduce:]

1. Opened a yaml file

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [ide-yaml](https://github.com/liuderchi/ide-yaml) package 0.4.1

### Stack Trace

Uncaught Error: Connection is closed.

```
At /Users/miket/.atom/packages/ide-yaml/node_modules/vscode-jsonrpc/lib/main.js:606

Error: Connection is closed.
    at /packages/ide-yaml/node_modules/vscode-jsonrpc/lib/main.js:131:28)
    at throwIfClosedOrDisposed (/packages/ide-yaml/node_modules/vscode-jsonrpc/lib/main.js:606:19)
    at Object.sendNotification (/packages/ide-yaml/node_modules/vscode-jsonrpc/lib/main.js:660:13)
    at LanguageClientConnection._sendNotification (/packages/ide-yaml/node_modules/atom-languageclient/build/lib/languageclient.js:242:15)
    at LanguageClientConnection.didChangeWatchedFiles (/packages/ide-yaml/node_modules/atom-languageclient/build/lib/languageclient.js:143:10)
    at ServerManager.projectFilesChanged (/packages/ide-yaml/node_modules/atom-languageclient/build/lib/server-manager.js:233:33)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /Applications/Atom.app/Contents/Resources/app/src/project.js:297:40
    at PathWatcher.onNativeEvents (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:671:15)
    at /Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:567:31
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at NativeWatcher.onEvents (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:448:26)
    at handler (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:177:15)
```

### Commands

```
  2x -9:41.2.0 settings-view:install-packages-and-themes (atom-pane.pane.active)
     -9:26.9.0 core:backspace (input.hidden-input)
  3x -9:25.5.0 core:confirm (input.hidden-input)
  2x -6:14.1.0 application:add-project-folder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-ide-ui 0.5.3 
autocomplete-python 1.10.3 
busy-signal 1.4.3 
ide-yaml 0.4.1 
intentions 1.1.5 
linter 2.2.0 
linter-js-yaml 1.2.8 
linter-ui-default 1.6.10 
```

**Comment by liuderchi** [comment] 2017-10-28 02:39
@trebolcinco thanks for reporting this issue.
Please try [these steps][workaround] to remove cached storage as temporarily workaround.

Currently we are not sure what the root cause is.
Please help provide more info for following questions.

- does this stills happens after terminating Atom app then start Atom again?
- does this issue always happen whenever you open a yaml file?


[workaround]: https://github.com/liuderchi/ide-yaml/issues/9#issuecomment-335511083 "workaround"

**Comment by brianmhunt** [comment] 2017-10-31 13:27
It looks like this is a dupe of #9 (or at least the same root cause)

**Comment by liuderchi** [comment] 2017-12-13 02:03
@brianmhunt thanks for your report 👍 
Will close this issue since it's duplicated of #9.

**Closed by liuderchi** 2017-12-13 02:03 UTC
Labels: help wanted, lsp-client, need-reproduce
